server:
  port: 8091 #服务端口
###起个名字作为服务名称(该服务注册到eureka注册中心的名称，比如商品服务)
spring:
  application:
    name: app-item
###服务注册到eureka注册中心的地址
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10  # 发呆时间，即服务续约到期时间（缺省为90s）
  client:
    service-url:
#      defaultZone: http://127.0.0.1:8100/eureka
      #添加密码的方式
      defaultZone: http://mj:123@127.0.0.1:8100/eureka
    ###因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心
    register-with-eureka: true
    ###是否需要从eureka上检索服务
    fetch-registry: true
